name: nandrlon
description: A new Flutter project.

publish_to: 'none'

version: 1.4.7+86

environment:
  sdk: ">=2.11.0 <3.0.0"

dependencies:

  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.5
  location: ^5.0.0
  flutter_polyline_points: ^1.0.0
  firebase_database: ^10.0.16
  google_fonts: ^4.0.4
  flutter_svg: ^0.23.0+1
  pin_code_fields: ^8.0.1
  percent_indicator: ^4.2.3
  url_launcher: ^6.1.10
  flutter_map: ^2.2.0
  firebase_auth: ^4.3.0
  firebase_core: ^2.8.0
  cloud_firestore: ^4.4.5
  firebase: ^9.0.3
  cached_network_image: ^3.2.1
  mask_text_input_formatter: ^2.9.0
  shared_preferences: ^2.1.1
  google_maps_flutter: ^2.2.6
  map_launcher: ^3.2.0
  intl: ^0.17.0
  flutter_image_slideshow: ^0.1.6
  syncfusion_flutter_datepicker: ^21.2.3
  image_picker: ^0.8.7+1
  file_picker: ^5.2.10
  modal_bottom_sheet: ^2.1.2
  geolocator: ^11.1.0
  geocoding: ^3.0.0
  json_annotation: ^4.7.0
  loader_overlay: ^3.0.3
  flutter_pdfview: ^1.3.2
  path_provider: ^2.0.15
  flutter_share: ^2.0.0
  firebase_messaging: ^14.3.0
  flutter_local_notifications: ^8.2.0
  get_storage: ^2.1.1
  flutter_html: ^2.2.1
  easy_localization: ^3.0.7
  firebase_remote_config: ^3.0.15
  package_info_plus: ^3.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:

  uses-material-design: true

  assets:
    - assets/image/
    - assets/image/file/
    - assets/svg/
    - assets/json/
    - assets/json/doctor-call/
    - assets/translations/


  fonts:
    - family: KaushanScript-Regular
      fonts:
        - asset: assets/fonts/KaushanScript-Regular.otf

    - family: aileron
      fonts:
        - asset: assets/fonts/aileron/Aileron-Regular.otf
        - asset: assets/fonts/aileron/Aileron-SemiBold.otf
          weight: 600
        - asset: assets/fonts/aileron/Aileron-Bold.otf
          weight: 700

    - family: DroidKufi
      fonts:
        - asset: assets/fonts/DroidKufi/DroidKufi-Regular.ttf
        - asset: assets/fonts/DroidKufi/DroidKufi-Bold.ttf
          weight: 700
